# Dockerfile.frontend
FROM node:20-slim

WORKDIR /app

# Copy package.json & package-lock.json
COPY frontend/package*.json ./

# Install dependencies
RUN npm ci

# Install Expo CLI globally
RUN npm install -g expo-cli @expo/ngrok

# Copy rest of frontend code
COPY frontend/ .

EXPOSE 19000 19001 19002

CMD ["npm", "run", "start:expo"]
