# Use Node.js 20 image
FROM node:20

# Set working directory
WORKDIR /backend

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy backend code
COPY backend/ .

# Expose port
EXPOSE 5000

# Start backend
CMD ["npx", "nodemon", "./src/index.js", "--watch", "./src"]
